const express=require("express");
const cors=require("cors");
const path=require("path");
const fs=require("fs");
const app=express();
app.use(cors());
app.use(express.json({limit:"50mb"}));

const MAYAH="https://mayah.co/api/v1/publico/list_public/link/cfec25a072e111eb94fee71bd50f2bf6";
const DATA_DIR=process.env.DATA_DIR || (fs.existsSync("/data") ? "/data" : __dirname);
fs.mkdirSync(DATA_DIR,{recursive:true});
const DATA=path.join(DATA_DIR,"catalog-data.json");
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"nutrilife";
const GITHUB_TOKEN=process.env.GITHUB_TOKEN||"";
const GITHUB_REPO=process.env.GITHUB_REPO||"benja20br-source/Nutrilife";
const GITHUB_BRANCH=process.env.GITHUB_BRANCH||"main";
const GITHUB_FILE=process.env.GITHUB_FILE||"catalog-data.json";
const SITE_URL="https://nutrilife-n7rq.onrender.com";

async function githubRequest(url,options={}){return fetch(url,{...options,headers:{Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28",Authorization:`Bearer ${GITHUB_TOKEN}`,...(options.headers||{})}})}
async function saveCatalogToGitHub(data){
  if(!GITHUB_TOKEN)return {saved:false,reason:"GITHUB_TOKEN no configurado"};
  const url=`https://api.github.com/repos/${GITHUB_REPO}/contents/${GITHUB_FILE}`;
  const current=await githubRequest(`${url}?ref=${encodeURIComponent(GITHUB_BRANCH)}`);let sha;
  if(current.ok){const j=await current.json();sha=j.sha}else if(current.status!==404)throw new Error(`GitHub GET ${current.status}`);
  const content=Buffer.from(JSON.stringify(data,null,2),"utf8").toString("base64");
  const body={message:"Actualizar catálogo NUTRILIFE",content,branch:GITHUB_BRANCH};if(sha)body.sha=sha;
  const r=await githubRequest(url,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
  if(!r.ok){const t=await r.text();throw new Error(`GitHub PUT ${r.status}: ${t.slice(0,300)}`)}return {saved:true}
}
async function loadCatalogFromGitHub(){
  if(!GITHUB_TOKEN)return null;try{const url=`https://api.github.com/repos/${GITHUB_REPO}/contents/${GITHUB_FILE}?ref=${encodeURIComponent(GITHUB_BRANCH)}`;const r=await githubRequest(url);if(!r.ok)return null;const j=await r.json();if(!j.content)return null;return JSON.parse(Buffer.from(j.content.replace(/\n/g,""),"base64").toString("utf8"))}catch(e){console.error("No se pudo leer catálogo desde GitHub:",e.message);return null}
}
function seedCatalog(){const products=JSON.parse(fs.readFileSync(path.join(__dirname,"products.json"),"utf8"));const config=JSON.parse(fs.readFileSync(path.join(__dirname,"config.json"),"utf8"));return {products,config,updatedAt:new Date().toISOString()}}
function readLocalCatalog(){try{return JSON.parse(fs.readFileSync(DATA,"utf8"))}catch(e){return null}}
async function readCatalog(){const remote=await loadCatalogFromGitHub();if(remote){try{fs.writeFileSync(DATA,JSON.stringify(remote,null,2))}catch(e){}return remote}const local=readLocalCatalog();if(local)return local;const fresh=seedCatalog();try{fs.writeFileSync(DATA,JSON.stringify(fresh,null,2))}catch(e){}return fresh}
async function writeCatalog(data){data.updatedAt=new Date().toISOString();fs.writeFileSync(DATA,JSON.stringify(data,null,2));return saveCatalogToGitHub(data)}
function auth(req,res,next){if(req.headers["x-admin-password"]!==ADMIN_PASSWORD)return res.status(401).json({ok:false,message:"Contraseña incorrecta"});next()}

app.get("/api/catalog",async(req,res)=>{try{const d=await readCatalog();const products=d.products.map(p=>({code:p.code,name:p.name,cat:p.cat,desc:p.desc||"",image:p.image||null,available:p.available!==false,prices:{100:publicPrice(p,100),500:publicPrice(p,500),1000:publicPrice(p,1000)}}));res.json({products,updatedAt:d.updatedAt,promotions:d.config?.promotions||[]})}catch(e){res.status(500).json({message:e.message})}});
function marginFor(p,g){const specific={100:p.margin100,500:p.margin500,1000:p.margin1000}[g];if(specific!=null&&specific!=="")return Number(specific);return Number(p.margin??40)}
function publicPrice(p,g){const margin=marginFor(p,g);const cost=Number(p.cost||0);return Math.round(cost*g/1000*(1+margin/100))}
function escHtml(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;")}
function slugify(s){return String(s??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
function productUrl(p){return `${SITE_URL}/producto/${encodeURIComponent(p.code)}-${slugify(p.name)}`}
function categoryUrl(cat){return `${SITE_URL}/categoria/${slugify(cat)}`}
function productDescription(p){return p.desc||`${p.name} de NUTRILIFE. Disponible en 100 g, 500 g y 1 kg. Pedidos online por WhatsApp en Gran Mendoza.`}
function productPage(p){
  const url=productUrl(p), available=p.available!==false, image=p.image?`<img src="${escHtml(p.image)}" alt="${escHtml(p.name)} en NUTRILIFE" loading="eager">`:"";
  const offers=[100,500,1000].map(g=>`<li><strong>${g===1000?"1 kg":g+" g"}</strong>: $${publicPrice(p,g).toLocaleString("es-AR")}</li>`).join("");
  const jsonLd={"@context":"https://schema.org","@type":"Product","name":p.name,"description":productDescription(p),"url":url,"category":p.cat||"Alimentos","brand":{"@type":"Brand","name":"NUTRILIFE"},...(p.image?{image:[p.image]}:{}),"offers":{"@type":"Offer","url":url,"priceCurrency":"ARS","price":publicPrice(p,100),"availability":available?"https://schema.org/InStock":"https://schema.org/OutOfStock","seller":{"@type":"Organization","name":"NUTRILIFE"}}};
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escHtml(p.name)} | NUTRILIFE Gran Mendoza</title><meta name="description" content="${escHtml(productDescription(p))}"><meta name="robots" content="${available?"index,follow":"noindex,follow"}"><link rel="canonical" href="${url}"><meta property="og:type" content="product"><meta property="og:site_name" content="NUTRILIFE"><meta property="og:title" content="${escHtml(p.name)} | NUTRILIFE Gran Mendoza"><meta property="og:description" content="${escHtml(productDescription(p))}">${p.image?`<meta property="og:image" content="${escHtml(p.image)}">`:``}<script type="application/ld+json">${JSON.stringify(jsonLd).replace(/</g,"\\u003c")}</script><style>body{margin:0;font-family:Arial,sans-serif;color:#263025;background:#f8f6f0}.top{background:#40512f;color:#fff;text-align:center;padding:9px;font-weight:bold;font-size:12px}.wrap{max-width:900px;margin:auto;padding:28px 20px}.brand{display:flex;align-items:center;gap:10px;text-decoration:none;color:#40512f;font-weight:900;letter-spacing:3px;font-size:24px}.brand img{width:48px;height:48px;object-fit:contain}.card{margin-top:25px;background:#fff;border:1px solid #e4dfd5;border-radius:22px;padding:25px;display:grid;grid-template-columns:minmax(240px,420px) 1fr;gap:30px;align-items:center}.photo{background:#f3eee3;border-radius:18px;min-height:320px;display:flex;align-items:center;justify-content:center;overflow:hidden;font-size:70px}.photo img{width:100%;height:100%;min-height:320px;object-fit:contain}.cat{color:#40512f;font-weight:bold}.price{font-size:24px;font-weight:900;color:#40512f}.cta{display:inline-block;background:#40512f;color:#fff;text-decoration:none;padding:13px 18px;border-radius:10px;font-weight:bold;margin-top:10px}@media(max-width:700px){.card{grid-template-columns:1fr}.photo{min-height:240px}.photo img{min-height:240px}}</style></head><body><div class="top">🌱 NUTRILIFE · GRAN MENDOZA · PEDIDOS POR WHATSAPP</div><main class="wrap"><a class="brand" href="/" aria-label="Volver a NUTRILIFE"><img src="/logo.svg" alt="NUTRILIFE">NUTRILIFE</a><div class="card"><div class="photo">${image||"🥜"}</div><div><div class="cat">${escHtml(p.cat||"Alimentos")}</div><h1>${escHtml(p.name)}</h1><p>${escHtml(productDescription(p))}</p><h2>Presentaciones y precios</h2><ul>${offers}</ul><p>${available?"Disponible para pedido online.":"Producto no disponible actualmente."}</p>${available?`<a class="cta" href="/?producto=${encodeURIComponent(p.code)}#productos">COMPRAR / VER EN LA TIENDA</a>`:`<a class="cta" href="/">VER OTROS PRODUCTOS</a>`}</div></div><p><a href="/">← Volver a NUTRILIFE</a></p></main></body></html>`;
}
function categoryPage(cat,products){
  const url=categoryUrl(cat), available=products.filter(p=>p.available!==false), title=`${cat} en Gran Mendoza | NUTRILIFE`, desc=`Comprá ${cat.toLowerCase()} en NUTRILIFE Gran Mendoza. Elegí 100 g, 500 g o 1 kg y pedí por WhatsApp.`;
  const cards=available.map(p=>`<article><h2><a href="${productUrl(p)}">${escHtml(p.name)}</a></h2><p>${escHtml(productDescription(p))}</p><p><strong>Desde $${publicPrice(p,100).toLocaleString("es-AR")} / 100 g</strong></p></article>`).join("");
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escHtml(title)}</title><meta name="description" content="${escHtml(desc)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${url}"><script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage","name":title,"description":desc,"url":url,"isPartOf":{"@type":"WebSite","name":"NUTRILIFE","url":SITE_URL}}).replace(/</g,"\\u003c")}</script><style>body{margin:0;font-family:Arial,sans-serif;color:#263025;background:#f8f6f0}.wrap{max-width:950px;margin:auto;padding:30px 20px}.brand{color:#40512f;text-decoration:none;font-size:24px;font-weight:900;letter-spacing:3px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:15px}article{background:#fff;border:1px solid #e4dfd5;border-radius:16px;padding:18px}a{color:#40512f}@media(max-width:650px){.grid{grid-template-columns:1fr}}</style></head><body><main class="wrap"><a class="brand" href="/">NUTRILIFE</a><h1>${escHtml(title)}</h1><p>${escHtml(desc)}</p><div class="grid">${cards||"<p>No hay productos disponibles en esta categoría.</p>"}</div><p><a href="/">← Ver todos los productos</a></p></main></body></html>`;
}

app.get("/api/admin/catalog",auth,async(req,res)=>{try{res.json(await readCatalog())}catch(e){res.status(500).json({ok:false,message:e.message})}});
app.put("/api/admin/catalog",auth,async(req,res)=>{try{const body=req.body;if(!body||!Array.isArray(body.products)||!body.config)return res.status(400).json({ok:false,message:"Datos inválidos"});body.config.promotions=Array.isArray(body.config.promotions)?body.config.promotions:[];const result=await writeCatalog({products:body.products,config:body.config});res.json({ok:true,updatedAt:body.updatedAt,persistent:"github",github:result})}catch(e){res.status(500).json({ok:false,message:e.message})}});
app.get("/api/mayah",async(req,res)=>{try{const r=await fetch(MAYAH,{cache:"no-store"});const j=await r.json();res.json(j)}catch(e){res.status(502).json({status:"ERROR",message:"No se pudo consultar Mayah"})}});
app.post("/api/admin/sync-mayah",auth,async(req,res)=>{try{const r=await fetch(MAYAH,{cache:"no-store"});const j=await r.json();const d=await readCatalog();const incoming=j.response?.productos||[];let changed=0;for(const x of incoming){const p=d.products.find(y=>String(y.code)===String(x.codigo));if(p&&x.precio!=null){p.cost=Number(x.precio);changed++}if(p&&x.imagen&&!p.image)p.image=x.imagen}await writeCatalog(d);res.json({ok:true,changed,updatedAt:d.updatedAt})}catch(e){res.status(502).json({ok:false,message:"No se pudo sincronizar Mayah"})}});

const LOGO_SVG=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1080 1350" role="img" aria-label="NUTRILIFE"><rect width="1080" height="1350" fill="#5b610b"/><g fill="#f7efe3" font-family="Arial,Helvetica,sans-serif" font-weight="900" text-anchor="middle"><text x="540" y="690" font-size="150" letter-spacing="4">NUTRILIFE</text></g><g fill="none" stroke="#f7efe3" stroke-width="28" stroke-linecap="round"><path d="M425 755 C470 850 610 875 690 790"/></g><path d="M700 555 C715 510 735 475 770 450 C765 500 745 540 710 575 Z" fill="#f7efe3"/><path d="M710 575 C725 535 745 505 765 490" fill="none" stroke="#5b610b" stroke-width="12" stroke-linecap="round"/></svg>`;
app.get("/logo.svg",(req,res)=>{res.set("Cache-Control","no-store");res.type("image/svg+xml");const file=path.join(__dirname,"logo.svg");if(fs.existsSync(file))return res.send(fs.readFileSync(file,"utf8"));return res.send(LOGO_SVG)});

// SEO: sitemap dinámico con productos y categorías disponibles.
app.get("/sitemap.xml",async(req,res)=>{try{const d=await readCatalog();const available=d.products.filter(p=>p.available!==false);const cats=[...new Set(available.map(p=>p.cat).filter(Boolean))];const lastmod=d.updatedAt?new Date(d.updatedAt).toISOString().slice(0,10):new Date().toISOString().slice(0,10);const urls=[{loc:SITE_URL+'/',priority:'1.0',changefreq:'daily'},{loc:SITE_URL+'/categoria/frutos-secos',priority:'0.8',changefreq:'daily'},...cats.filter(c=>slugify(c)!=='frutos-secos').map(c=>({loc:categoryUrl(c),priority:'0.7',changefreq:'daily'})),...available.map(p=>({loc:productUrl(p),priority:'0.8',changefreq:'daily'}))];const xml='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(u=>`<url><loc>${escHtml(u.loc)}</loc><lastmod>${lastmod}</lastmod><changefreq>${u.changefreq}</changefreq><priority>${u.priority}</priority></url>`).join('')+'</urlset>';res.set("Cache-Control","public, max-age=3600");res.type("application/xml").send(xml)}catch(e){res.status(500).type("text/plain").send("No se pudo generar el sitemap")}});
app.get("/robots.txt",(req,res)=>{try{const file=path.join(__dirname,"robots.txt");if(!fs.existsSync(file))return res.status(404).type("text/plain").send("Robots no encontrado");res.set("Cache-Control","public, max-age=3600");res.type("text/plain").send(fs.readFileSync(file,"utf8"));}catch(e){res.status(500).type("text/plain").send("No se pudo cargar robots.txt")}});

// Páginas SEO de productos/categorías. Los productos marcados como no disponibles no se indexan.
app.get("/producto/:identifier",async(req,res)=>{try{const d=await readCatalog();const identifier=decodeURIComponent(req.params.identifier);const code=identifier.split('-')[0];const p=d.products.find(x=>String(x.code)===String(code));if(!p)return res.status(404).send("Producto no encontrado");res.type("html").send(productPage(p))}catch(e){res.status(500).send("No se pudo cargar el producto")}});
app.get("/categoria/:slug",async(req,res)=>{try{const d=await readCatalog();const slug=slugify(req.params.slug);const products=d.products.filter(p=>slugify(p.cat)===slug);if(!products.length)return res.status(404).send("Categoría no encontrada");const cat=products[0].cat;res.type("html").send(categoryPage(cat,products))}catch(e){res.status(500).send("No se pudo cargar la categoría")}});

app.get(["/","/index.html"],(req,res)=>{try{const html=fs.readFileSync(path.join(__dirname,"index.html"),"utf8");const brand=`<div class="nutrilife-brand" aria-label="NUTRILIFE"><img src="/logo.svg?v=2" alt="NUTRILIFE"></div>`;const styles=`<style>.nutrilife-brand{width:100%;height:96px;background:#5a600b;display:flex;align-items:center;justify-content:center;overflow:hidden}.nutrilife-brand img{width:170px;height:96px;object-fit:contain;display:block}.nutrilife-brand+nav{margin-top:0}@media(max-width:600px){.nutrilife-brand{height:82px}.nutrilife-brand img{width:145px;height:82px}}</style>`;
const seoSchema={"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":SITE_URL+"/#organization","name":"NUTRILIFE","url":SITE_URL+"/","logo":SITE_URL+"/logo.svg","telephone":"+54 9 261 217-3125","areaServed":{"@type":"AdministrativeArea","name":"Gran Mendoza, Mendoza, Argentina"}},{"@type":"WebSite","@id":SITE_URL+"/#website","name":"NUTRILIFE","url":SITE_URL+"/","publisher":{"@id":SITE_URL+"/#organization"},"inLanguage":"es-AR"},{"@type":"WebPage","@id":SITE_URL+"/#webpage","url":SITE_URL+"/","name":"NUTRILIFE | Frutos secos, harinas y legumbres en Gran Mendoza","description":"Frutos secos, mixes, granos, harinas y legumbres en Gran Mendoza. Comprá online en 100 g, 500 g o 1 kg y pedí por WhatsApp.","isPartOf":{"@id":SITE_URL+"/#website"},"about":{"@id":SITE_URL+"/#organization"},"inLanguage":"es-AR"}]};
const seo=`<script type="application/ld+json">${JSON.stringify(seoSchema).replace(/</g,"\\u003c")}</script>`;
res.type("html").send(html.replace("</head>",seo+"</head>").replace("<body>","<body>"+styles+brand))}catch(e){res.status(500).send("No se pudo cargar NUTRILIFE")}});
app.use(express.static(__dirname));
app.get(/.*/,(req,res)=>res.sendFile(path.join(__dirname,"index.html")));
app.listen(process.env.PORT||3000,()=>console.log("NUTRILIFE lista"));